### ISSUE TITLE
Error when uploading app (ERROR ITMS-90535)

### ISSUE THREAD

**Issue by ebbybeh** [robovm/robovm-robopods#85] opened 2016-01-13 17:41 UTC
I have been trying to update my app with the latest GPGS robopods but have another snag. 

I get the following errors when uploading the app using the application loader: 

		ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/IOSLauncher.app/GooglePlus.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
		ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/IOSLauncher.app/GooglePlus.bundle/GPPCommonSharedResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
		ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/IOSLauncher.app/GooglePlus.bundle/GPPShareboxSharedResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
		ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/IOSLauncher.app/gpg.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

The fix is simple: delete the CFBundleExecutable property from the info.plist files in each of the bundles. The problem: I don't know where to access those bundles as I imported the packages via gradle.

**Comment by ebbybeh** [comment] 2016-01-13 17:43
Whoops, just noticed this: https://github.com/robovm/robovm-robopods/issues/61

**Comment by BlueRiverInteractive** [comment] 2016-01-17 01:41
Duplicate of #61

**Closed by BlueRiverInteractive** 2016-01-17 01:41 UTC
Labels: duplicate
